### ISSUE TITLE
Randomly not working on 2.06 and 0.6.0

### ISSUE THREAD

**Issue by Arkhorse** [Xpazeman/tld-house-lights#7]
Tried multiple locations in Milton (Grey Mothers house, Bank) and none of the lights are working. The switches work, but nothing else.
[Latest.log](https://github.com/Xpazeman/tld-house-lights/files/10483728/Latest.log)

EDIT:
Seems reloading the scene (exit the interior, re-enter) can fix the issue. However it can also cause the issue. So maybe something went wrong with persistency? Not sure since I dont mod the game ATM.

**Comment by Xpazeman** [comment]
Not reproduceable and probably due to some conflict or race condition
